name: Build

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .\BahamutGUI.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  # BUILD_CONFIGURATION: Release
  # BUILD_PLATFORM: x64

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        BUILD_CONFIGURATION: [debug, release]
        BUILD_PLATFORM: [x86, x64]
        os: [windows-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup MSbuild project
      if: matrix.os == 'windows-latest'
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: tools\windows\premake5.exe vs2019

    - name: Setup gmake project
      if: matrix.os == 'ubuntu-latest'
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./tools/linux/premake5 gmake2

    - name: Build with MSBuild
      working-directory: ${{env.GITHUB_WORKSPACE}}
      if: matrix.os == 'windows-latest'
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{matrix.BUILD_CONFIGURATION}} /p:Platform=${{matrix.BUILD_PLATFORM}} ${{env.SOLUTION_FILE_PATH}}
    
    - name: Build with make
      working-directory: ${{env.GITHUB_WORKSPACE}}
      if: matrix.os == 'ubuntu-latest'
      run: make config=${{matrix.BUILD_CONFIGURATION}}_${{matrix.BUILD_PLATFORM}}