name: Build (Linux)

on: [push]

env:
  BUILD_PLATFORM: x86_64

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_CONFIGURATION: [debug, release]
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get -y install xorg-dev

    - name: Use Premake to setup project
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./tools/linux/premake5 gmake2

    - name: Build with make
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: make config=${{matrix.BUILD_CONFIGURATION}}_${{env.BUILD_PLATFORM}}
    